-- Generado por catalogo.py: axiomas de cada teorema (deben ser sólo propext,
-- Classical.choice y Quot.sound).
import All

#print axioms CertifiedFiniteODE.sampledCLM_apply
#print axioms CertifiedFiniteODE.hasFDerivAt_sampled
#print axioms CertifiedFiniteODE.jacobianOf_sampledCLM
#print axioms CertifiedFiniteODE.sampledCLM_sub_le
#print axioms CertifiedFiniteODE.certified_cos_ode
#print axioms CertifiedODEReduction.certified_parameter_reduction
#print axioms CosineCertificate.cos_lower_of_rel_error
#print axioms CosineCertificate.cos_ge_of_rel_error
#print axioms CosineCertificate.taylor_bound
#print axioms CosineCertificate.finite_trajectory_error
#print axioms CosineCertificate.finite_cos_certificate
#print axioms EventSystems.event_hasFDerivAt
#print axioms ExactLinearCertificate.cos_certificate_of_bounds
#print axioms ExactLinearCertificate.cosv_smul
#print axioms ExactLinearCertificate.continuousAt_cosv
#print axioms ExactLinearCertificate.keepS_smul
#print axioms ExactLinearCertificate.norm_linear_part_eq
#print axioms ExactLinearCertificate.finite_trajectory_error_exact
#print axioms ExactLinearCertificate.exact_le_Rvar_bound
#print axioms ExactLinearCertificate.finite_cos_certificate_exact
#print axioms ExactLinearCertificate.certified_cos_ode_exact
#print axioms ExactLinearCertificate.tendsto_cos_delta
#print axioms ExactLinearCertificate.eventually_cos_delta_gt
#print axioms ExactLinearCertificate.exists_cos_delta_gt
#print axioms ExactLinearCertificate.local_cos_ode
#print axioms FirstOrderErrorBound.sqNorm_nonneg
#print axioms FirstOrderErrorBound.columnEnergy_nonneg
#print axioms FirstOrderErrorBound.removedColumnEnergy_nonneg
#print axioms FirstOrderErrorBound.removedParamSq_nonneg
#print axioms FirstOrderErrorBound.sum_split
#print axioms FirstOrderErrorBound.total_eq_kept_add_removed
#print axioms FirstOrderErrorBound.response_sub_reduced
#print axioms FirstOrderErrorBound.first_order_error_sq_bound
#print axioms FirstOrderErrorBound.first_order_error_bound
#print axioms FirstOrderErrorBound.removedParamSq_le
#print axioms FirstOrderErrorBound.first_order_error_from_removed_fraction
#print axioms FirstOrderErrorBound.first_order_error_from_Rvar
#print axioms GlobalExistence.clampB_apply
#print axioms GlobalExistence.clampB_nonneg
#print axioms GlobalExistence.clampB_le
#print axioms GlobalExistence.clampB_pos
#print axioms GlobalExistence.clampB_eq
#print axioms GlobalExistence.dist_clampB_le
#print axioms GlobalExistence.clampB_mem
#print axioms GlobalExistence.convex_box
#print axioms GlobalExistence.isCompact_box
#print axioms GlobalExistence.lipschitzOn_box
#print axioms GlobalExistence.exists_global_solution
#print axioms ODEParamDiff.isSolOn_self
#print axioms ODEParamDiff.extend_solution
#print axioms ODEParamDiff.exists_solution_Icc
#print axioms GreedySelection.greedy_ok
#print axioms GreedySelection.greedy_subset
#print axioms GreedySelection.greedy_discard_permanent
#print axioms GreedySelection.supportedOn_mono
#print axioms GreedySelection.okKappa_anti
#print axioms GreedySelection.okVIF_anti
#print axioms GreedySelection.greedy_kappa_vif_guarantee
#print axioms Identifiability.IsLSMin.inner_residual_eq_zero
#print axioms Identifiability.ls_response_stability
#print axioms Identifiability.ls_param_stability
#print axioms Identifiability.ls_unique
#print axioms Identifiability.one_le_kappa_mul_sigmaMin
#print axioms Identifiability.ls_kappa_stability
#print axioms Identifiability.ls_param_kappa_stability
#print axioms Identifiability.ls_vif_coordinate_stability
#print axioms Identifiability.vif_geometric_of_inverse
#print axioms Identifiability.ls_vif_inverse_stability
#print axioms IntervalInit.mul_mem_corners
#print axioms IntervalInit.imul_sound
#print axioms IntervalInit.ival_sound
#print axioms IntervalInit.initI_sound
#print axioms IntervalInit.strict_final_initI
#print axioms KineticCheck.KExpr'.isNonneg_sound
#print axioms KineticCheck.KExpr'.isPos_sound
#print axioms KineticCheck.KExpr'.okOrth_sound
#print axioms KineticCheck.KExpr'.vanishes_sound
#print axioms KineticCheck.KExpr'.qp_sound
#print axioms KineticCheck.checkModel_spec
#print axioms KineticCheck.checkModel_sound
#print axioms KineticCheck.checked_model_hasFDerivAt
#print axioms KineticCheck.checked_segments_hasFDerivAt
#print axioms KineticCheck.qvec_apply
#print axioms KineticCheck.posParams_qvec
#print axioms KineticCheck.nonneg_qvec
#print axioms KineticCheck.checked_model_final
#print axioms KineticCheck.checked_segments_final
#print axioms KineticCheck.checkInit_spec
#print axioms KineticCheck.nonneg_zero
#print axioms KineticCheck.init_differentiable
#print axioms KineticCheck.init_nonneg
#print axioms KineticCheck.checked_model_final_init
#print axioms KineticNetwork.eval_netExpr
#print axioms KineticNetwork.ok_netExpr
#print axioms KineticNetwork.coef_mul_nonneg
#print axioms KineticNetwork.checkNet_sound
#print axioms KineticNetwork.eval_varfree
#print axioms KineticNetwork.ssum_nonneg
#print axioms KineticNetwork.lowerpos_sound
#print axioms KineticNetwork.linBound_sound
#print axioms KineticNetwork.sum_c_coef
#print axioms KineticNetwork.sum_c_netExpr
#print axioms KineticNetwork.checkGrowth_sound
#print axioms KineticNetwork.checkNet_append
#print axioms KineticNetwork.checkGrowth_append
#print axioms KineticNetwork.c_ge_one
#print axioms KineticNetwork.network_exists
#print axioms KineticNetwork.network_final
#print axioms KineticNetwork.network_final_init
#print axioms KineticNetwork.network_segments_final
#print axioms KineticRegularity.KExpr.contDiffAt_eval
#print axioms KineticRegularity.KExpr.isOpen_ok
#print axioms KineticRegularity.KExpr.ok_of_noDen
#print axioms KineticRegularity.KExpr.ok_mm
#print axioms KineticRegularity.KExpr.ok_hill
#print axioms KineticRegularity.KExpr.ok_hillR
#print axioms KineticRegularity.isOpen_domain
#print axioms KineticRegularity.contDiffOn_field
#print axioms KineticRegularity.domain_eq_univ
#print axioms KineticRegularity.kinetic_hasFDerivAt
#print axioms KineticRegularity.kinetic_local_cos
#print axioms LinearizedFit.lin_le_scaled
#print axioms LinearizedFit.fit_upper_of_lin
#print axioms LinearizedFit.fit_lower_of_lin
#print axioms LocalExistence.clampE_apply
#print axioms LocalExistence.abs_clamp_sub_le
#print axioms LocalExistence.dist_clampE_le
#print axioms LocalExistence.lipschitz_clampE
#print axioms LocalExistence.clampE_eq
#print axioms LocalExistence.clampE_zero
#print axioms LocalExistence.norm_clampE_le
#print axioms LocalExistence.exists_solutions_near
#print axioms LocalExistence.hasFDerivAt_of_nominal_solution
#print axioms NominalCertificate.local_cos_from_nominal
#print axioms NumericalRobustness.fd_column_error
#print axioms NumericalRobustness.columnEnergy_eq_norm_sq
#print axioms NumericalRobustness.rvar_certified_from_approx
#print axioms NumericalRobustness.opNorm_le_frobenius
#print axioms NumericalRobustness.kappa_certified_from_approx
#print axioms NumericalRobustness.vif_certified_from_approx
#print axioms OutputComposition.output_sq_bound
#print axioms OutputComposition.output_uniform_bound
#print axioms OutputComposition.log_lipschitz
#print axioms OutputComposition.log10_lipschitz
#print axioms ODEParamDiff.uniform_linearization
#print axioms ODEParamDiff.tube_gronwall
#print axioms ODEParamDiff.norm_comp_inl_le
#print axioms ODEParamDiff.clm_prod_apply_split
#print axioms ODEParamDiff.lipschitzOn_slice
#print axioms ODEParamDiff.hasFDerivAt_solution_param_init
#print axioms ODEParamDiff.hasFDerivAt_solution_param_on
#print axioms ODEParamDiff.hasFDerivAt_solution_param
#print axioms PatternMechanisms.not_okKappa_of_kernel
#print axioms PatternMechanisms.ls_not_unique_of_kernel
#print axioms PatternMechanisms.opposing_pair_kernel
#print axioms PatternMechanisms.exact_reduction_of_zero_energy
#print axioms Poda.prune_spec
#print axioms Poda.exists_minimal_admissible
#print axioms PositivityInvariance.pos_apply
#print axioms PositivityInvariance.pos_nonneg
#print axioms PositivityInvariance.pos_eq_self
#print axioms PositivityInvariance.dist_pos_le
#print axioms PositivityInvariance.sub_pos_apply
#print axioms PositivityInvariance.pos_apply_eq_zero
#print axioms PositivityInvariance.isClosed_nonneg
#print axioms PositivityInvariance.hasDerivAt_negSq
#print axioms PositivityInvariance.nonneg_core
#print axioms PositivityInvariance.nonneg_of_quasiPositive
#print axioms PositivityInvariance.kinetic_nonneg
#print axioms PositivityInvariance.kinetic_hasFDerivAt_of_nonneg
#print axioms PositivityInvariance.exampleModel_orth
#print axioms PositivityInvariance.exampleModel_qp
#print axioms PositivityInvariance.exampleModel_nonneg
#print axioms RefitMonotone.feas_mono
#print axioms RefitMonotone.fitErr_anti
#print axioms RefitMonotone.fitErr_union_le
#print axioms RefitMonotone.fitErr_le_erel
#print axioms RefitMonotone.admissible_mono
#print axioms RiccatiNetwork.exists_solution_riccati
#print axioms RiccatiNetwork.qval_sound
#print axioms RiccatiNetwork.qnn_sound
#print axioms RiccatiNetwork.var_le_phi
#print axioms RiccatiNetwork.linV_sound
#print axioms RiccatiNetwork.prodV_sound
#print axioms RiccatiNetwork.quadV_sound
#print axioms RiccatiNetwork.tot_sound
#print axioms RiccatiNetwork.riccati_final
#print axioms ScaledError.norm_sub_smul_sq
#print axioms ScaledError.scaled_error_ge
#print axioms ScaledError.scaled_error_eq
#print axioms ScaledError.scaled_error_cos
#print axioms ScaledError.min_rel_error_eq
#print axioms SensitivityLipschitz.gronwall_zero_init
#print axioms SensitivityLipschitz.norm_comp_inl_le
#print axioms SensitivityLipschitz.norm_comp_inr_le
#print axioms SensitivityLipschitz.g_lipschitz
#print axioms SensitivityLipschitz.norm_pair_sub_le
#print axioms SensitivityLipschitz.traj_lipschitz
#print axioms SensitivityLipschitz.sens_bound
#print axioms SensitivityLipschitz.sens_lipschitz
#print axioms SpectralConditioning.inner_gram
#print axioms SpectralConditioning.gram_isSymmetric
#print axioms SpectralConditioning.finrank_eq
#print axioms SpectralConditioning.lam_antitone
#print axioms SpectralConditioning.gram_evec
#print axioms SpectralConditioning.sq_norm_apply_evec
#print axioms SpectralConditioning.lam_nonneg
#print axioms SpectralConditioning.sq_norm_apply_eq_sum
#print axioms SpectralConditioning.sq_norm_eq_sum
#print axioms SpectralConditioning.sq_norm_bounds
#print axioms SpectralConditioning.lam_le_max
#print axioms SpectralConditioning.min_le_lam
#print axioms SpectralConditioning.norm_bounds
#print axioms SpectralConditioning.opNorm_eq_sqrt_lamMax
#print axioms SpectralConditioning.sqrt_lamMin_mul_le
#print axioms SpectralConditioning.le_sqrt_lamMin
#print axioms SpectralConditioning.ls_kappa_stability_spectral
#print axioms SpectralConditioning.matCLM_apply
#print axioms SpectralConditioning.inner_matCLM
#print axioms SpectralConditioning.gram_toEuclideanLin
#print axioms SpectralConditioning.vif_matrix_inverse
#print axioms SpectralConditioning.ls_vif_matrix_stability
#print axioms StrictExistence.lo_nonneg
#print axioms StrictExistence.lo_le
#print axioms StrictExistence.clampQ_apply
#print axioms StrictExistence.clampQ_mem
#print axioms StrictExistence.boxQ_sPos
#print axioms StrictExistence.clampQ_pos
#print axioms StrictExistence.clampQ_eq
#print axioms StrictExistence.dist_clampQ_le
#print axioms StrictExistence.convex_boxQ
#print axioms StrictExistence.isCompact_boxQ
#print axioms StrictExistence.lipschitzOn_boxQ
#print axioms StrictExistence.exists_global_solution_strict
#print axioms StrictNetwork.keq_sound
#print axioms StrictNetwork.qge1_sound
#print axioms StrictNetwork.qgt1_sound
#print axioms StrictNetwork.addlb_sound
#print axioms StrictNetwork.subub_sound
#print axioms StrictNetwork.ub_qvec
#print axioms StrictNetwork.sign_sound
#print axioms StrictNetwork.sNonneg_sound
#print axioms StrictNetwork.expLe1_sound
#print axioms StrictNetwork.sPos_sound
#print axioms StrictNetwork.sOk_sound
#print axioms StrictNetwork.snp_sound
#print axioms StrictNetwork.summand_sound
#print axioms StrictNetwork.bndB_const
#print axioms StrictNetwork.bndB_div_lowerpos
#print axioms StrictNetwork.bndB_summand
#print axioms StrictNetwork.bndB_mul
#print axioms StrictNetwork.bndB_add
#print axioms StrictNetwork.bndB_frac_mul_l
#print axioms StrictNetwork.bndB_frac_mul_r
#print axioms StrictNetwork.bndB_pair
#print axioms StrictNetwork.bndB_pair'
#print axioms StrictNetwork.consB_mul_l
#print axioms StrictNetwork.consB_mul_r
#print axioms StrictNetwork.consB_div_lowerpos
#print axioms StrictNetwork.bndB_congr
#print axioms StrictNetwork.consB_congr
#print axioms StrictNetwork.eval_pair
#print axioms StrictNetwork.eval_pair'
#print axioms StrictNetwork.consB_var
#print axioms StrictNetwork.consB_npow
#print axioms StrictNetwork.bndB_npow
#print axioms StrictNetwork.bndB_exp_np
#print axioms StrictNetwork.bndB_var
#print axioms StrictNetwork.bq_of
#print axioms StrictNetwork.cq_of
#print axioms StrictNetwork.bnd_sound
#print axioms StrictNetwork.term_qp
#print axioms StrictNetwork.term_decay
#print axioms StrictNetwork.checkNetS_sound
#print axioms StrictNetwork.term_growth
#print axioms StrictNetwork.checkGrowthS_sound
#print axioms StrictNetwork.c_ge_oneS
#print axioms StrictNetwork.strict_exists
#print axioms StrictNetwork.init_sPos
#print axioms StrictNetwork.strict_final_init
#print axioms TrajectoryErrorBound.keepS_apply
#print axioms TrajectoryErrorBound.norm_keepS_le
#print axioms TrajectoryErrorBound.clm_apply_eq_linResponse
#print axioms TrajectoryErrorBound.clm_keepS_eq_reducedResponse
#print axioms TrajectoryErrorBound.linear_part_bound
#print axioms TrajectoryErrorBound.sqrt_removedParamSq_le
#print axioms TrajectoryErrorBound.remainder_isLittleO
#print axioms TrajectoryErrorBound.trajectory_error_bound
#print axioms TrajectoryErrorBound.trajectory_error_from_Rvar
