import KineticCheck

/-! Modelo `Raimundez_PCB2020` traducido automáticamente de SBML por
`certificados/sbml_to_lean.py`. No editar a mano.

Estados (22): EGFR, EGFR_CET, EGFR_EGF, EGFR_EGF_2, pEGFR_EGF_2, pEGFR_EGF_2_i, MMET, MMET_2, pMMET_2, pMMET_2_i, MMET_EGFR, pMMET_pEGFR, pMMET_pEGFR_i, MMET_METinh, MMET_MMET_METinh, MMET_METinh_2, EGFR_MMET_METinh, RAS_GTP, pMAPK, pPI3K, pMPI3K, pAKT

Parámetros estimados θ (57): KD_EGFR_CET, KD_EGFR_EGF, KD_METinh, d_AKTtotal__MKN1_2_HS746T, d_AKTtotal__fm_2_hm, d_MAPKtotal__MKN1_2_HS746T, d_MAPKtotal__fm_2_hm, d_MPI3Ktotal__fm_2_hm, d_PI3Ktotal__fm_2_hm, d_RAStotal__MKN1_2_HS746T, d_RAStotal__fm_2_hm, d_kdeg_membran__MKN1_2_HS746T, d_kdeg_pEGFR_EGF_2_i__MKN1_2_HS746T, d_kexp_pEGFR_EGF_2_i__MKN1_2_HS746T, d_kimp_pEGFR_EGF_2__MKN1_2_HS746T, d_ksyn_EGFR__MKN1_2_HS746T, d_ksyn_EGFR__fm_2_hm, d_ksyn_MMET__fm_2_hm, ka_AKT__MKN1, ka_MAPK__MKN1, ka_PI3K__basal, ka_PI3K__pEGFR_EGF_2, ka_RAS__basal__MKN1, ka_RAS__pEGFR_EGF_2__MKN1, kbin_EGFR_CET, kbin_EGFR_EGF, kdeg_membran__MKN1, kdeg_pEGFR_EGF_2_i__MKN1, kdim_EGFR_EGF, kdim_MMET, kdim_MMET_EGFR, kdim_MMETinh, kexp_pEGFR_EGF_2_i__MKN1, ki_AKT__MKN1, ki_MAPK, ki_PI3K__MKN1, ki_RAS__MKN1, kimp_pEGFR_EGF_2__MKN1, kpho_EGFR_EGF, kpho_MMET, kpho_MMET_EGFR, ksyn_MMET__HS746T_fm, xi_ka_PI3K_pMMET_2, xi_ka_PI3K_pMMET_pEGFR, xi_ka_RAS_pMMET_2, xi_ka_RAS_pMMET_pEGFR, xi_kdeg_pMMET_2_i, xi_kdeg_pMMET_pEGFR_i, xi_kdim_MMET, xi_kdim_MMET_EGFR, xi_kexp_pMMET_2_i, xi_kexp_pMMET_pEGFR_i, xi_ki_MPI3K, xi_kimp_pMMET_2, xi_kimp_pMMET_pEGFR, xi_kpho_MMET, xi_kpho_MMET_EGFR
-/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

open KineticRegularity KineticCheck

namespace Models.Raimundez_PCB2020

def F : Fin 22 → KExpr 22 57 := ![
  (.sub (.add (.sub (.add (.add (.sub (.add (.sub (.sub (.mul (.qconst (1 : ℚ)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 15)) (.mul (.par 16) (.qconst (1 : ℚ))))))) (.mul (.mul (.qconst (1 : ℚ)) (.var 0)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.mul (.qconst (343 / 50 : ℚ)) (.qconst (1 : ℚ))) (.qconst (1 : ℚ)))) (.var 0)) (.par 24))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 1)) (.par 0)) (.par 24))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.mul (.qconst (161 / 1000 : ℚ)) (.qconst (1 : ℚ))) (.qconst (1 : ℚ)))) (.var 0)) (.par 25))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 2)) (.par 1)) (.par 25))) (.mul (.qconst (2 : ℚ)) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 32) (.exp (.mul (.qconst (1 : ℚ)) (.par 13))))) (.var 5)))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 0)) (.var 6)) (.par 30)) (.par 49))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 32) (.exp (.mul (.qconst (1 : ℚ)) (.par 13))))) (.var 12)) (.par 51))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 0)) (.var 13)) (.par 30)) (.par 49))),
  (.sub (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.mul (.qconst (343 / 50 : ℚ)) (.qconst (1 : ℚ))) (.qconst (1 : ℚ)))) (.var 0)) (.par 24)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 1)) (.par 0)) (.par 24))) (.mul (.mul (.qconst (1 : ℚ)) (.var 1)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))),
  (.sub (.sub (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.mul (.qconst (161 / 1000 : ℚ)) (.qconst (1 : ℚ))) (.qconst (1 : ℚ)))) (.var 0)) (.par 25)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 2)) (.par 1)) (.par 25))) (.mul (.qconst (2 : ℚ)) (.mul (.mul (.qconst (1 : ℚ)) (.npow (.var 2) 2)) (.par 28)))) (.mul (.mul (.qconst (1 : ℚ)) (.var 2)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))),
  (.sub (.sub (.mul (.mul (.qconst (1 : ℚ)) (.npow (.var 2) 2)) (.par 28)) (.mul (.mul (.qconst (1 : ℚ)) (.var 3)) (.par 38))) (.mul (.mul (.qconst (1 : ℚ)) (.var 3)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))),
  (.sub (.mul (.mul (.qconst (1 : ℚ)) (.var 3)) (.par 38)) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 37) (.exp (.mul (.qconst (1 : ℚ)) (.par 14))))) (.var 4))),
  (.sub (.sub (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 37) (.exp (.mul (.qconst (1 : ℚ)) (.par 14))))) (.var 4)) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 32) (.exp (.mul (.qconst (1 : ℚ)) (.par 13))))) (.var 5))) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 27) (.exp (.mul (.qconst (1 : ℚ)) (.par 12))))) (.var 5))),
  (.add (.sub (.sub (.add (.sub (.add (.sub (.sub (.mul (.qconst (1 : ℚ)) (.mul (.mul (.qconst (1 : ℚ)) (.par 41)) (.exp (.mul (.par 17) (.qconst (1 : ℚ)))))) (.mul (.mul (.qconst (1 : ℚ)) (.var 6)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ)))) (.var 6)) (.par 31))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 2)) (.var 13)) (.par 31))) (.mul (.qconst (2 : ℚ)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.npow (.var 6) 2)) (.par 29)) (.par 48)))) (.mul (.qconst (2 : ℚ)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 32) (.exp (.mul (.qconst (1 : ℚ)) (.par 13))))) (.var 9)) (.par 50)))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 6)) (.var 13)) (.par 29)) (.par 48))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 0)) (.var 6)) (.par 30)) (.par 49))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 32) (.exp (.mul (.qconst (1 : ℚ)) (.par 13))))) (.var 12)) (.par 51))),
  (.sub (.sub (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.npow (.var 6) 2)) (.par 29)) (.par 48)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 7)) (.par 39)) (.par 55))) (.mul (.mul (.qconst (1 : ℚ)) (.var 7)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ)))) (.var 7)) (.par 31))),
  (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 7)) (.par 39)) (.par 55)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 37) (.exp (.mul (.qconst (1 : ℚ)) (.par 14))))) (.var 8)) (.par 53))),
  (.sub (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 37) (.exp (.mul (.qconst (1 : ℚ)) (.par 14))))) (.var 8)) (.par 53)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 32) (.exp (.mul (.qconst (1 : ℚ)) (.par 13))))) (.var 9)) (.par 50))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 27) (.exp (.mul (.qconst (1 : ℚ)) (.par 12))))) (.var 9)) (.par 46))),
  (.sub (.sub (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 0)) (.var 6)) (.par 30)) (.par 49)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 10)) (.par 40)) (.par 56))) (.mul (.mul (.qconst (1 : ℚ)) (.var 10)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))),
  (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 10)) (.par 40)) (.par 56)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 37) (.exp (.mul (.qconst (1 : ℚ)) (.par 14))))) (.var 11)) (.par 54))),
  (.sub (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 37) (.exp (.mul (.qconst (1 : ℚ)) (.par 14))))) (.var 11)) (.par 54)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 32) (.exp (.mul (.qconst (1 : ℚ)) (.par 13))))) (.var 12)) (.par 51))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 27) (.exp (.mul (.qconst (1 : ℚ)) (.par 12))))) (.var 12)) (.par 47))),
  (.sub (.sub (.sub (.sub (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ)))) (.var 6)) (.par 31)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 2)) (.var 13)) (.par 31))) (.mul (.mul (.qconst (1 : ℚ)) (.var 13)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 6)) (.var 13)) (.par 29)) (.par 48))) (.mul (.qconst (2 : ℚ)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.npow (.var 13) 2)) (.par 29)) (.par 48)))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 0)) (.var 13)) (.par 30)) (.par 49))),
  (.sub (.sub (.add (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 6)) (.var 13)) (.par 29)) (.par 48)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ)))) (.var 7)) (.par 31))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ)))) (.var 14)) (.par 31))) (.mul (.mul (.qconst (1 : ℚ)) (.var 14)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))),
  (.sub (.add (.mul (.mul (.mul (.qconst (1 : ℚ)) (.npow (.var 13) 2)) (.par 29)) (.par 48)) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ)))) (.var 14)) (.par 31))) (.mul (.mul (.qconst (1 : ℚ)) (.var 15)) (.mul (.par 26) (.exp (.mul (.qconst (1 : ℚ)) (.par 11)))))),
  (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 0)) (.var 13)) (.par 30)) (.par 49)),
  (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.qconst (0 : ℚ)) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 22) (.exp (.qconst (0 : ℚ))))) (.var 17))) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 22) (.exp (.qconst (0 : ℚ))))) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 9)) (.mul (.par 10) (.qconst (1 : ℚ)))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 4)) (.var 17))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 4)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 9)) (.mul (.par 10) (.qconst (1 : ℚ)))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 5)) (.var 17))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 5)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 9)) (.mul (.par 10) (.qconst (1 : ℚ)))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 11)) (.par 45)) (.var 17))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 11)) (.par 45)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 9)) (.mul (.par 10) (.qconst (1 : ℚ)))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 12)) (.par 45)) (.var 17))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 12)) (.par 45)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 9)) (.mul (.par 10) (.qconst (1 : ℚ)))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 8)) (.par 44)) (.var 17))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 8)) (.par 44)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 9)) (.mul (.par 10) (.qconst (1 : ℚ)))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 9)) (.par 44)) (.var 17))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 23) (.exp (.qconst (0 : ℚ))))) (.var 9)) (.par 44)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 9)) (.mul (.par 10) (.qconst (1 : ℚ)))))))) (.mul (.mul (.qconst (1 : ℚ)) (.var 17)) (.mul (.par 36) (.exp (.qconst (0 : ℚ)))))),
  (.sub (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 17)) (.mul (.par 19) (.exp (.qconst (0 : ℚ))))) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 5)) (.mul (.par 6) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.var 17)) (.mul (.par 19) (.exp (.qconst (0 : ℚ))))) (.var 18))) (.mul (.mul (.qconst (1 : ℚ)) (.par 34)) (.var 18))),
  (.sub (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.mul (.mul (.qconst (1 : ℚ)) (.par 20)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 8) (.qconst (1 : ℚ)))))) (.mul (.mul (.qconst (1 : ℚ)) (.par 20)) (.var 19))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 4)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 8) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 4)) (.var 19))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 5)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 8) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 5)) (.var 19))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 11)) (.par 43)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 8) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 11)) (.par 43)) (.var 19))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 12)) (.par 43)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 8) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 12)) (.par 43)) (.var 19))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 8)) (.par 42)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 8) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 8)) (.par 42)) (.var 19))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 9)) (.par 42)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 8) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 9)) (.par 42)) (.var 19))) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 35) (.exp (.qconst (0 : ℚ))))) (.var 19))),
  (.sub (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.add (.sub (.mul (.mul (.qconst (1 : ℚ)) (.par 20)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 7) (.qconst (1 : ℚ)))))) (.mul (.mul (.qconst (1 : ℚ)) (.par 20)) (.var 20))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 4)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 7) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 4)) (.var 20))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 5)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 7) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 5)) (.var 20))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 11)) (.par 43)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 7) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 11)) (.par 43)) (.var 20))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 12)) (.par 43)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 7) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 12)) (.par 43)) (.var 20))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 8)) (.par 42)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 7) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 8)) (.par 42)) (.var 20))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 9)) (.par 42)) (.mul (.mul (.qconst (1 : ℚ)) (.qconst (1 : ℚ))) (.exp (.mul (.par 7) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.mul (.qconst (1 : ℚ)) (.par 21)) (.var 9)) (.par 42)) (.var 20))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 35) (.exp (.qconst (0 : ℚ))))) (.var 20)) (.par 52))),
  (.sub (.sub (.add (.sub (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 18) (.exp (.qconst (0 : ℚ))))) (.var 19)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 3)) (.mul (.par 4) (.qconst (1 : ℚ))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 18) (.exp (.qconst (0 : ℚ))))) (.var 19)) (.var 21))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 18) (.exp (.qconst (0 : ℚ))))) (.var 20)) (.mul (.qconst (1 : ℚ)) (.exp (.add (.mul (.qconst (1 : ℚ)) (.par 3)) (.mul (.par 4) (.qconst (1 : ℚ)))))))) (.mul (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 18) (.exp (.qconst (0 : ℚ))))) (.var 20)) (.var 21))) (.mul (.mul (.qconst (1 : ℚ)) (.mul (.par 33) (.exp (.qconst (0 : ℚ))))) (.var 21)))
]

theorem check : checkModel F = true := by decide +kernel

/-- Diferenciabilidad de la trayectoria (y positividad) para este modelo. -/
def diff := @checked_model_hasFDerivAt _ _ F check

end Models.Raimundez_PCB2020

#print axioms Models.Raimundez_PCB2020.diff
