import KineticCheck

/-! Modelo `Zheng_PNAS2012` traducido automáticamente de SBML por
`certificados/sbml_to_lean.py`. No editar a mano.

Estados (15): K27me0K36me0, K27me0K36me1, K27me1K36me0, K27me0K36me2, K27me1K36me1, K27me2K36me0, K27me0K36me3, K27me1K36me2, K27me2K36me1, K27me3K36me0, K27me1K36me3, K27me2K36me2, K27me3K36me1, K27me2K36me3, K27me3K36me2

Parámetros estimados θ (45): inflowp, k00_01, k00_10, k01_00, k01_02, k01_11, k02_01, k02_03, k02_12, k03_02, k03_13, k10_00, k10_11, k10_20, k11_01, k11_10, k11_12, k11_21, k12_02, k12_11, k12_13, k12_22, k13_03, k13_12, k13_23, k20_10, k20_21, k20_30, k21_11, k21_20, k21_22, k21_31, k22_12, k22_21, k22_23, k22_32, k23_13, k23_22, k30_20, k30_31, k31_21, k31_30, k31_32, k32_22, k32_31
-/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

open KineticRegularity KineticCheck

namespace Models.Zheng_PNAS2012

/-- Máscara de parámetros con valor nominal > 0 (los demás: signo arbitrario). -/
def pos : Fin 45 → Bool := ![true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]

def F : Fin 15 → KExpr 15 45 := ![
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.qconst (0 : ℚ)) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 0) (KExpr.par 1)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 1) (KExpr.par 3)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 0) (KExpr.par 2)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 2) (KExpr.par 11)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 0) (KExpr.par 1)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 1) (KExpr.par 3)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 1) (KExpr.par 5)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 14)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 1) (KExpr.par 4)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 3) (KExpr.par 6)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 0) (KExpr.par 2)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 2) (KExpr.par 11)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 2) (KExpr.par 12)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 15)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 2) (KExpr.par 13)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 5) (KExpr.par 25)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 1) (KExpr.par 4)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 3) (KExpr.par 6)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 3) (KExpr.par 8)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 18)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 3) (KExpr.par 7)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 6) (KExpr.par 9)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 2) (KExpr.par 12)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 15)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 1) (KExpr.par 5)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 14)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 16)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 19)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 17)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 28)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 2) (KExpr.par 13)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 5) (KExpr.par 25)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 5) (KExpr.par 26)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 29)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 5) (KExpr.par 27)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 9) (KExpr.par 38)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 3) (KExpr.par 7)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 6) (KExpr.par 9)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 6) (KExpr.par 10)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 10) (KExpr.par 22)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 3) (KExpr.par 8)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 18)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 16)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 19)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 21)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 32)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 20)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 10) (KExpr.par 23)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 5) (KExpr.par 26)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 29)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 4) (KExpr.par 17)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 28)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 30)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 33)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 31)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 12) (KExpr.par 40)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 5) (KExpr.par 27)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 9) (KExpr.par 38)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 9) (KExpr.par 39)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 12) (KExpr.par 41)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 6) (KExpr.par 10)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 10) (KExpr.par 22)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 20)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 10) (KExpr.par 23)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 10) (KExpr.par 24)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 13) (KExpr.par 36)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.add (KExpr.sub (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 7) (KExpr.par 21)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 32)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 30)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 33)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 34)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 13) (KExpr.par 37)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 35)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 14) (KExpr.par 43)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.add (KExpr.sub (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 9) (KExpr.par 39)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 12) (KExpr.par 41)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 8) (KExpr.par 31)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 12) (KExpr.par 40)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 12) (KExpr.par 42)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 14) (KExpr.par 44)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 34)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 13) (KExpr.par 37)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 10) (KExpr.par 24)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 13) (KExpr.par 36)) (KExpr.qconst (1 : ℚ))))),
  (KExpr.sub (KExpr.add (KExpr.sub (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 11) (KExpr.par 35)) (KExpr.qconst (1 : ℚ)))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 14) (KExpr.par 43)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 12) (KExpr.par 42)) (KExpr.qconst (1 : ℚ))))) (KExpr.mul (KExpr.qconst (1 : ℚ)) (KExpr.div (KExpr.mul (KExpr.var 14) (KExpr.par 44)) (KExpr.qconst (1 : ℚ)))))
]

theorem check : checkModel pos F = true := by decide +kernel

/-- Diferenciabilidad de la trayectoria (y positividad) para este modelo. -/
def diff := @checked_model_hasFDerivAt _ _ pos F check

end Models.Zheng_PNAS2012

#print axioms Models.Zheng_PNAS2012.diff
